### PR TITLE
CORE-412: purge vault support

### PR DESCRIPTION
**Pull request by ianmcorvidae**
This is mostly a `git revert -m 1 ccfc97e967e1d4856c0cd88cff1e1709ede75a5a` plus some massaging -- specifically to bring the dependencies back to current and some other weird stuff like extra blank lines. Putting this up now, but I'm still testing it.

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
Main review I'd really like is to know what I'll need to change to have this work with k8s VICE. If that already uses the `--debug-config` option then it's pretty easy, just gotta switch it to use `--config`. I pretty much know what to do to make it work with road-runner, that'll be another PR.

**Comment by ianmcorvidae** [comment]
Got the info to check for myself. It's currently using the `debug-config` option via the short name of `-z`: https://github.com/cyverse-de/vice-file-transfers/blob/master/main.go#L179

So it should be an easy enough fix to change that to `-c` or `--config`

**Review by johnworth — APPROVED** [review]
:shipit: 

Looks good to me. We'll know quickly whether other changes are needed.

**Comment by ianmcorvidae** [comment]
Cool, thanks for the review. I'll work on making vice-file-transfers and road-runner changes, at the least, before merging, of course.

**Pull request merged**
